### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [mattmc3/zsh-safe-rm#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by mattmc3** [comment]
No problem - wanted to verify I picked something compatible with the shell-safe-rm submodule. Thankfully, MIT all the things.
