### ISSUE TITLE
How to use hard/unsafe rm command ?

### ISSUE THREAD

**Issue by collegeimprovements** [mattmc3/zsh-safe-rm#2]
There are some situations when we need to use `unsafe rm` command. Is there a way to do that ?

**Comment by mattmc3** [comment]
You can always put a leading backslash on your rm to get back to the builtin for a one-time command.

https://unix.stackexchange.com/questions/39291/run-a-command-that-is-shadowed-by-an-alias

I suppose you could also add an unsafe-rm alias to reference the builtin, but `\rm` seems like the  more appropriate way to me. maybe I should update the README with that.

**Comment by mattmc3** [comment]
README updated.
