### ISSUE TITLE
How to empty trash ?

### ISSUE THREAD

**Issue by collegeimprovements** [mattmc3/zsh-safe-rm#3]
Hi @mattmc3, it works great. 
With `unsafe-rm` we can delete the file permanently.
However it doesn't work on macos for emptying trash.
How can we empty trash from command-line ?

**Comment by mattmc3** [comment]
Do you mean something like `unsafe-rm -rf ~/.Trash/*`?

**Comment by collegeimprovements** [comment]
Yes...something like that. e.g. `sudo unsafe-rm -rf ~/.Trash/*` or something that can empty the trash. Currently I get this kind of error (e.g. match no foud, operation not permitted etc).

![Screenshot 2020-05-06 at 2 03 30 PM](https://user-images.githubusercontent.com/1519705/81155248-5f9fbf00-8fa2-11ea-8dd4-41f12a2662de.png)

**Comment by collegeimprovements** [comment]
Currently I'm using alfred .. which has `empty trash` option. And it's working well.

**Comment by mattmc3** [comment]
Your Trash folder may not actually be at ~/.Trash. If you have iCloud sync on, your folder may be `/Users/arpit/Library/Mobile\ Documents/com~apple~CloudDocs/.Trash/`.
